### PR TITLE
Improve letters animation

### PR DESCRIPTION
**Pull request by s0ber**
@evol Hey man, I need your review here.
Hope you're doing great, btw!

### CODE REVIEW

**Comment by s0ber** [comment]
@evol Your turn now! We need to add glitch effect ASAP:
https://ihatetomatoes.net/how-to-create-css-glitch-effect/

**Comment by evoL** [comment]
I was _just_ about to LGTM it! :stuck_out_tongue:

**Comment by evoL** [comment]
Will look at implementing the glitch effect in the evening :wink:

**Comment by s0ber** [comment]
@evoL I've prepared video demo in case you are very busy X)
https://vk.com/video314787834_456239091

Also, posted a link to the repo in video description and then realized that code is not merged... I had no choice and just merged it. People may saw previous version, which was ugly.

Thanks for the help with glitches! Here is some music for inspiration ;)
https://www.youtube.com/watch?v=G3r79zqkKeg

**Comment by evoL** [comment]
Nice stuff!

**Pull request merged**
